In [1]:
# LIBRARIES
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('winequality-red.csv')
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [3]:
x = df.iloc[:, :-1].values #independent variable
y = df.iloc[:, -1].values #dependent variable

In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.10, random_state = 0)

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit_transform(x_train)
sc.transform(x_test)

array([[ 1.4276637 , -0.32797   ,  0.81413583, ..., -0.91332883,
         0.58793664,  0.35907387],
       [-0.132032  ,  1.60330664, -1.3890692 , ...,  0.32361012,
        -0.74862075, -0.7645082 ],
       [ 0.44563308, -1.32119799,  0.30176257, ..., -0.32741038,
         1.05282617,  1.20176043],
       ...,
       [ 0.15680054,  0.63766832, -0.10813604, ..., -0.19720628,
        -0.34184241, -0.38998084],
       [-0.9985296 , -0.162432  , -1.3890692 , ...,  0.84442652,
        -0.63239836,  1.76355146],
       [ 1.08106466, -0.71422533,  0.66042386, ...,  0.45381422,
         1.16904855,  0.07817836]])

In [6]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state = 10, max_depth = 10, max_features = 'auto',n_estimators = 50)

rf.fit(x_train, y_train)
y_pred = rf.predict(x_train)

import sklearn.metrics as metrics
print(metrics.confusion_matrix(y_train, y_pred))
print(metrics.accuracy_score(y_train, y_pred))

[[  7   0   2   0   0   0]
 [  0  30  13   4   0   0]
 [  0   0 600  17   0   0]
 [  0   0  26 539   0   0]
 [  0   0   4  13 168   0]
 [  0   0   0   2   1  13]]
0.9430159833217512


In [7]:
y_pred = rf.predict(x_test)

print(metrics.confusion_matrix(y_test, y_pred))
print(metrics.accuracy_score(y_test, y_pred))

[[ 0  0  0  1  0  0]
 [ 0  0  4  2  0  0]
 [ 0  0 57  7  0  0]
 [ 0  0 12 57  4  0]
 [ 0  0  0  6  8  0]
 [ 0  0  0  1  1  0]]
0.7625
